<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <RootNamespace>Jellyfin.Plugin.BecauseYouWatched</RootNamespace>
    <AssemblyVersion>1.1.4.0</AssemblyVersion>
    <FileVersion>1.1.4.0</FileVersion>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration/configPage.html" />
  </ItemGroup>

</Project>
